# File: .github/workflows/web.yml
on: push
jobs:
  build:
    runs-on: windows-latest
    name: web workflow
    steps:
      - name: build
        run: dotnet build Source/Web/TailwindPOS.csproj --configuration Release